targets:
  $default:
    sources:
      - lib/**
      - schema.graphql
    builders:
      artemis:
        options:
          scalar_mapping:
            - graphql_type: Date
              dart_type: int
          schema_mapping:
            - schema: schema.graphql
              queries_glob: lib/external/*.graphql
              output: lib/external/graphql_api.dart