name: cek_in

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logger: ^1.1.0
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  shared_preferences: ^2.0.8
  graphql_flutter: ^5.0.0
  flutter_secure_storage: ^5.0.2
  json_serializable: ^6.0.1
  meta: ^1.7.0
  gql: ^0.13.0
  qr_code_scanner: ^0.6.1
  grouped_list: ^4.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_svg: ^1.0.0

dependency_overrides:
  gql_exec: 0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  artemis: ^7.2.6-beta
  build_runner: ^2.1.5

flutter:

  uses-material-design: true

  assets:
    - assets/icon/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
